version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=financial_chatbot
    depends_on:
      - mongo
    volumes:
      - ./src:/app
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=financial_chatbot
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
